import Link from "@/node_modules/next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav>
          <Link href="/">Home</Link> &nbsp; &nbsp;
          <Link href="/posts">Post</Link>
        </nav>
        <main> {children} </main>
      </body>
    </html>
  );
}
